name: Build Executable

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography pillow pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "TookaTarh_DocManager" app.py

    - name: Upload Executable Directory
      uses: actions/upload-artifact@v4
      with:
        name: TookaTarh_Executable_Program
        path: dist/TookaTarh_DocManager/
